Polish README
spring-cloud-stream-app-starters/field-value-counter pull request #6
Opened 2017-08-15 22:02 UTC by sobychacko

2017-08-16 15:58 UTC, artembilan requested changes

2017-08-16 15:58 UTC, artembilan commented on spring-cloud-starter-stream-sink-field-value-counter/README.adoc
> +* `JSON String`
I think we should describe `content-type` header for all these valid payload types.
when it is `String`, the content-type should be `text/plain` or `application/json`.
And seems for me there is a special content type for the `Tuple`.

2017-08-16 15:58 UTC, artembilan commented on spring-cloud-starter-stream-sink-field-value-counter/README.adoc
> +You can find the corresponding binder based projects here. You can then cd into one one of the folders and build it:
I think we should consider to present this sentence out of the code block.
See my change for the `aggregator`: https://github.com/spring-cloud-stream-app-starters/aggregator/pull/9/files#diff-84c171210225cbda875c9ddc438ce2abR108

2017-08-17 00:14 UTC, sobychacko commented on spring-cloud-starter-stream-sink-field-value-counter/README.adoc
> +* `JSON String`
@artembilan String - `text/plain`, POJO/Map - `applicaiton/octet-stream` and what will be the content type when Tuple is used, do you know?

2017-08-18 19:29 UTC, artembilan commented on spring-cloud-starter-stream-sink-field-value-counter/README.adoc
> +* `JSON String`
@sobychacko ,

sorry for delay.
Have been able to find it. See `MessageConverterUtils.X_SPRING_TUPLE`. Looks like this is SCSt feature.
I would really prefer to align `Content-Type` header with the real `payload`.
Thanks

2017-08-22 07:51 UTC, ericbottard commented on spring-cloud-starter-stream-sink-field-value-counter/README.adoc
> +You can find the corresponding binder based projects here. You can then cd into one one of the folders and build it:
👍

2017-08-22 07:56 UTC, ericbottard commented on spring-cloud-starter-stream-sink-field-value-counter/README.adoc
> +* `JSON String`
Indeed, @artembilan 's suggestion seems to make sense. But then, is the two-section `Input` approach (with a `Headers` and `Payload` subsection) really appropriate? I assume this problem is going to arise elsewhere

2017-08-29 21:51 UTC, sobychacko commented
merged the PR.

2017-08-29 21:51 UTC, closed without merging